### ISSUE TITLE
Support mmap() with fixed addresses

### ISSUE THREAD

**Issue by senier** [Componolit/componolit-old#111]
Choosing a pre-defined address as a `mmap()` target is unsupported in Genode's libc right now. ART's custom ELF loader and many tests rely on that functionality. The following tests fail for that reason:

* libart-compiler tests (cf. #86)
   * OatTest.WriteRead
   * OatTest.EmptyTextSection
   * OatTest.DexFileInputCheckOutput
   * OatTest.DexFileInputCheckOutputLow4GB
   * OatTest.ZipFileInputCheckOutput

**Comment by senier** [comment]
Naive support for fixed addresses does not work. The reason is how `alloc()` is currently realized in libc.

First, the requested memory is allocated using the `alloc_aligned()` method of the local allocator. Should that fail, new backing store is added using the `expand()` operation with an exponentially growing block size. `expand()` allocates a new RAM dataspace of the respective block size and attaches it to the local address space. This may fail due to lack of RAM, lack of capabilities or a conflict in the region map (i.e. the new region overlaps with an already attached region). If successful, the new range is attached to the local allocator to be available for new allocation attempts. Finally, a bit of meta-data is allocated from that local allocator to hold a new object of type `Dataspace` to represent the newly added backing store.

The naive approach to fixed addresses is to extend `Libc::Mem_alloc_impl::alloc` with an additional `in_addr` with the usual semantics: arbitrary memory is allocated if it is 0, otherwise it is used as a fixed address. In this case, `alloc_addr()` is used instead of `alloc_aligned()`. If this fails, `expand()` is again used to add new backing store. A new parameter `in_addr` determines whether that backing store is attached to a fixed address or an arbitrary local address.

The solution does not work as the allocation of the new metadata inside `expand()` ends up at the requested fixed address. A subsequent allocation with that fixed address fails as it got allocated to the dataspace metadata already. Allocating metadata at the end of the new chunk using `alloc_addr()` mitigates the issue in some cases but fails for consecutive fixed areas.

Apparently metadata allocation should be done with a different allocator, at least for the fixed address case. The metadata allocator, however, also needs some functionality like `expand()` if it runs out of memory.

Idea to move forward:

* Derive from Allocator_avl and add an `allocate_foo()` that unifies fixed and arbitrary allocations (should remove the ugly multiple case distinctions)
* Add an `expand()`-like operation to the allocator that takes a separate metadata allocator
* Maybe even unify the try-allocate/expand/allocate cycle
* Use the new allocator for libc allocations together with an additional allocator for fixed-address metadata

@nfeske: Does this make any sense, do you see a more suitable solution for that issue?

**Comment by nfeske** [comment]
Wherever we need to manually place virtual memory areas, we use managed dataspaces (via the RM service):
# The RM service is used to allocate a relatively large region map (managed dataspace), let's say 512 MiB, which is just empty at this point.
# The managed dataspace is attached at the local address space at a fixed address via `attach_at`. This step effectively reserves the window of the PDs virtual address space according to the region-map size.
# Whenever a real memory object is allocated to be mapped at a fixed address, we create a dataspace and attach it to the managed dataspace at the corresponding offset. Of course, the virtual address range of the memory object must reside within the range of the managed dataspace.

Examples of this approach are the stack area and the linker area. Since metadata can be allocated outside this scheme, conflicts like the one you observed cannot happen.

However, I do not see an easy way to hide this mechanism transparently behind the mmap interface. But admittedly, I haven't looked deeply into to. May it be feasible to tailor the mechanism to the actual use case? (I guess, placing JIT-generated code in the virtual address space?)

That all said, I have to share that we are not completely happy with the current libc allocator infrastructure. Internally, we are discussion possible ways for improvements / replacements in the mid term. Splitting metadata from the allocated blocks is definitely a concern of us (also wrt mitigating heap-smashing attacks). But we haven't decided for any concrete way forward yet.
