### ISSUE TITLE
Custom session interface

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit-old#137]
The terminal session interface currently does not provide semantics to provide connection handling such as opening or closing connections. The semantics provided to sessions by Genode are insufficient since the server cannot close a connection.

A solution could be a custom terminal session that adds these semantics through additional signals.
Also sending meta data to provide state through the terminal session could be an option (yet might also be more useful as a custom session type).

**Comment by nfeske** [comment]
Without having looked at your use case in detail, I wonder if instead of introducing a new interface, you may be able to communicate the out-of-band state via the existing report-ROM mechanism. With this approach, you would route both a terminal session (or one per connection?) and a ROM session (presenting arbitrary higher-level state as XML). The terminal session(s) would carry the payload whereas the ROM session would communicate the higher-level state.

I applied this approach for Genode fundamental session-handling mechanism - the "session_requests" ROM provided by parents to child services. So I'm optimistic that it may be a good generally applicable pattern.

**Comment by jklmnn** [comment]
That sounds like a good idea, I actually haven't thought about this yet, thanks!
